import turtle
s=turtle.Screen()
t=turtle.Turtle()

color=input ('Please pick a colour: ')
shape=input ('Please choose an object: ')
if color in('black','red','green','blue','cyan','yellow','magenta','brown'):
    t.fillcolor(color)
    if shape=='truck':
        t.begin_fill()
        t.dot (50)
        t.forward (300)
        t.dot (50)
        t.left(90)
        t.circle(150,180)
        t.end_fill()
        t.hideturtle()

    elif shape=='bird':
    
        t.begin_fill()
        t.circle(150,180)
        t.left(180)
        t.forward(25)
        t.left(130)
        t.forward (30)
        t.circle(25)
        t.penup()
        t.goto(0,0)
        t.pendown()
        t.left(45)
        t.circle(150,90)
        t.right(90)
        t.forward(30)
        t.goto(0,300)
        t.end_fill()
        t.hideturtle()
    elif shape=='flower':
    
        t.pensize(5)
        t.pencolor('green')
        t.right(90)
        t.forward(150)
        t.goto(0,0)
        t.pensize(15)
        t.pencolor('purple')
        t.begin_fill()
        t.circle(50,90)
        t.left(90)
        t.circle(50,90)
#makes one pettle
        t.circle(50,90)
        t.left(90)
        t.circle(50,90)
        t.circle(50,90)
        t.left(90)
        t.circle(50,90)
        t.circle(50,90)
        t.left(90)
        t.circle(50,90)
        t.end_fill()
    #insert another step here for center
        t.dot(15,'yellow')
        t.penup()
        t.forward(150)
    #ask about writing name for base
        t.pencolor('black')
        t.fillcolor('brown')
        t.begin_fill()
        t.right(90)
        t.forward(30)
        t.pendown()
        t.left (135)
        t.forward (50)
        t.left(90)
        t.forward (50)
        t.left (135)
        t.end_fill()
        t.hideturtle()
    else :
        print('sorry try another shape')

else :
    print('sorry try another colour')
