import turtle
s=turtle.Screen()
t=turtle.Turtle ()
t.pensize(5)
t.left (45)
t.pencolor('purple')
t.forward(40)
t.pencolor('red')
t.left(90)
t.forward(40)
t.left(90)
t.pencolor('purple')
t.forward(40)
t.pencolor('red')
t.left(90)
t.forward(40)
